- name: kubeadm join
  command: "kubeadm join  --discovery-token-unsafe-skip-ca-verification --token {{ hostvars[groups.master[0]]['token'].stdout }} {{ hostvars[groups.master[0]]['ansible_default_ipv4']['address'] }}:6443"
  args:
    creates: /etc/kubernetes/kubelet.conf

# TODO: check how --discovery-token-ca-cert-hash sha256:{{ hostvars[groups.master[0]]['master_node_ca_hash']['stdout_lines'][0] }}  can be changed to avoid this error: Failed to request cluster info, will try again: [Get https://192.168.99.54:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: x509: certificate is valid for 10.96.0.1, 141.72.191.110, not 192.168.99.54]